# Generated by Django 4.0.2 on 2023-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fields',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owners',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
