# Generated by Django 4.0.2 on 2023-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapi', '0002_alter_farms_id_alter_fields_id_alter_owners_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldId', models.IntegerField()),
                ('cropType', models.CharField(max_length=500)),
                ('datePlanted', models.DateField()),
                ('amountPlanted', models.CharField(max_length=500)),
            ],
        ),
    ]
