# Generated by Django 4.1.5 on 2023-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapi', '0004_crops_farmid_crops_ownerid_fields_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='amountPlanted',
            field=models.IntegerField(),
        ),
    ]
